[build-system]
requires = ["setuptools", "wheel", "matplotlib"]
build-backend = "setuptools.build_meta"

[project]
name = "S2TXA"
version = "1.0.0"
description = "Extract slip direction and slip plane from the activated deformation mechanism"
keywords = ["ovito", "ovito-extension"]
authors = [{name = "Paul Lafourcade", email = "paul.lafourcade@cea.fr"}]
maintainers = [{name = "Paul Lafourcade", email = "paul.lafourcade@cea.fr"}]
license = {text = "GPLv3"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ovito >= 3.12.0",
]

[project.urls]
repository = "https://github.com/lafourcadep/S2TXA"

[project.entry-points.'OVITO.ViewportOverlay']
"S2TXA Pole Projection" = "S2TXA:S2TXAPoleFigureOverlay"
    
[project.entry-points.'OVITO.Modifier']
"S2TXA" = "S2TXA:S2TXA"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:module 'sre_parse' is deprecated:DeprecationWarning",
    "ignore:module 'sre_constants' is deprecated:DeprecationWarning",
]
